### ISSUE TITLE
Reporting on Timeline but not Activity w/ Module

### ISSUE THREAD

**Issue by nanodeath** [2e3s/awatcher#24]
Hi...I have an installation of ActivityWatch I set up a couple days ago when I ran into https://github.com/ActivityWatch/activitywatch/issues/1036, and the recommendation was to install awatcher. Since I already have ActivityWatch installed, I thought I'd use the module version instead of the bundle version. However, it's not working correctly. My Timeline shows stuff (including `not-afk` events and `aw-watcher-web-firefox` stuff, but the Activity section is completely empty, every tab.

I downloaded and installed https://github.com/2e3s/awatcher/releases/download/v0.2.7/aw-awatcher_0.2.7-1_amd64.deb.
Then I followed the directions for updating the config, so now `~/.config/activitywatch/aw-qt/aw-qt.toml` has this content:

```toml
[aw-qt]
autostart_modules = ["aw-server", "aw-awatcher"]

[aw-qt-testing]
#autostart_modules = ["aw-server", "aw-watcher-afk", "aw-watcher-window"]
```

I then restarted my computer to pick up the changes.

## Environment

```
/etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04.4 LTS"
```

ActivityWatch v0.13.1
awatcher v0.2.7-1
GNOME 42.9 w/ Wayland
