### ISSUE TITLE
No Tray Icon (KDE)

### ISSUE THREAD

**Issue by cameronj86** [2e3s/awatcher#41]
Everything else is working as expected I believe, so not a huge priority tbh. 

I used to run the standalone modules before transitioning over to the bundled version, so my (un)educated guess is that there might be some overlap there perhaps? 

I checked `~/.config/activitywatch/aw-qt.toml` and it is just the following:
```toml
[aw-qt]
autostart_modules = ["aw-server","aw-watcher-mpv","aw-awatcher","aw-sync","aw-watcher-media-player"] #Wayland Config

[aw-qt-testing]
#autostart_modules = ["aw-server", "aw-watcher-afk", "aw-watcher-window","aw-watcher-mpv","aw-watcher-mpd"]

#autostart_modules = ["aw-server", "aw-watcher-afk", "aw-watcher-window","aw-watcher-mpv"] #X11 Config
#,"aw-watcher-mpd" #Not working so I removed it to stop the minor error when I launch the server
```
I tried changing `aw-server` -> `aw-server-rust` and commenting out `[aw-qt-testing]` as well just now on a whim but doesn't appear to make any difference either. I'm at the 'throw it against the wall and see what sticks' phase and figured I should ask someone before I break something important lol.
